"""empty message

Revision ID: 22539d9a20e7
Revises: 648d82b7e14d
Create Date: 2019-09-02 17:48:31.778990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22539d9a20e7'
down_revision = '648d82b7e14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trips', 'owners', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'owner')
    # ### end Alembic commands ###
