"""empty message

Revision ID: 648d82b7e14d
Revises: f5b8ec8b2d2b
Create Date: 2019-08-31 20:50:33.286292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648d82b7e14d'
down_revision = 'f5b8ec8b2d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
