"""empty message

Revision ID: 69764b02ad9c
Revises: 22539d9a20e7
Create Date: 2019-09-04 16:16:43.289692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69764b02ad9c'
down_revision = '22539d9a20e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'password_hash')
    # ### end Alembic commands ###
