"""empty message

Revision ID: b5032e9b1bb9
Revises: 
Create Date: 2019-08-29 11:21:15.150317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5032e9b1bb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('staff_no', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('staff_no')
    )
    op.create_index(op.f('ix_staffs_email'), 'staffs', ['email'], unique=True)
    op.create_index(op.f('ix_staffs_name'), 'staffs', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_plate', sa.String(length=10), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_number_plate'), 'assets', ['number_plate'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_plate', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('conductor', sa.String(length=255), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('fare', sa.String(length=10), nullable=True),
    sa.Column('station', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['number_plate'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fare'),
    sa.UniqueConstraint('passengers')
    )
    op.create_index(op.f('ix_trips_conductor'), 'trips', ['conductor'], unique=False)
    op.create_index(op.f('ix_trips_driver'), 'trips', ['driver'], unique=False)
    op.create_index(op.f('ix_trips_route'), 'trips', ['route'], unique=False)
    op.create_index(op.f('ix_trips_staff_name'), 'trips', ['staff_name'], unique=False)
    op.create_index(op.f('ix_trips_station'), 'trips', ['station'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_station'), table_name='trips')
    op.drop_index(op.f('ix_trips_staff_name'), table_name='trips')
    op.drop_index(op.f('ix_trips_route'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver'), table_name='trips')
    op.drop_index(op.f('ix_trips_conductor'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_assets_number_plate'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staffs_name'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_email'), table_name='staffs')
    op.drop_table('staffs')
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
