"""empty message

Revision ID: bb9080797d79
Revises: f6c4ce219778
Create Date: 2019-09-05 12:13:59.321371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9080797d79'
down_revision = 'f6c4ce219778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trips_fare_key', 'trips', type_='unique')
    op.drop_constraint('trips_passengers_key', 'trips', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trips_passengers_key', 'trips', ['passengers'])
    op.create_unique_constraint('trips_fare_key', 'trips', ['fare'])
    # ### end Alembic commands ###
