"""empty message

Revision ID: f6c4ce219778
Revises: f276c9e8a42a
Create Date: 2019-09-05 08:48:35.623149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c4ce219778'
down_revision = 'f276c9e8a42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'password_hash')
    # ### end Alembic commands ###
